apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-mqa-scoring-api
  labels:
    app: fdk-mqa-scoring-api
    fdk.service: fdk-mqa-scoring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-mqa-scoring-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdk-mqa-scoring-api
        fdk.service: fdk-mqa-scoring-api
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: fdk-mqa-scoring-api
          image: fdk-mqa-scoring-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: common
                  key: NAMESPACE
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: POSTGRES_PORT
            - name: POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: POSTGRES_DB_NAME
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: POSTGRES_PASSWORD
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: API_KEY
            - name: CORS_ORIGIN_PATTERNS
              valueFrom:
                secretKeyRef:
                  name: fdk-metadata-quality
                  key: CORS_ORIGIN_PATTERNS
          resources:
            requests:
              memory: "1400Mi"
              cpu: "10m"
            limits:
              memory: "1400Mi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8082
          readinessProbe:
            httpGet:
              path: /ready
              port: 8082
      restartPolicy: Always
