/*
 * Metadata Quality
 *
 * Metadata quality of datasets
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dimension {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "metrics")]
    pub metrics: Vec<crate::models::Metric>,
    #[serde(rename = "score")]
    pub score: i32,
    #[serde(rename = "max_score")]
    pub max_score: i32,
}
