/*
 * Metadata Quality
 *
 * Metadata quality of datasets
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SuccessResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl SuccessResponse {
    pub fn new(success: bool) -> SuccessResponse {
        SuccessResponse {
            success,
            message: None,
        }
    }

    pub fn with_message(success: bool, message: String) -> SuccessResponse {
        SuccessResponse {
            success,
            message: Some(message),
        }
    }
} 